server:
  port: 8083
spring:  
  application:
    name: api-gateway
  cloud:    gateway:      discovery:        locator:          enabled: false
          lower-case-service-id: true      routes:      - id: users-status-check
        uri: lb://user-ws
        predicates:        - Path=/user-ws/users/status/check
        - Method=GET
        - Header=Authorization, Bearer (.*)
        filters:
        - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
        - AuthorizationHeaderFilter
        
      - id: users-ws-login
        uri: lb://user-ws
        predicates:
        - Path=/user-ws/users/login
        - Method=POST
        filters:
        - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      
      - id: users-ws
        uri: lb://user-ws
        predicates:
        - Path=/user-ws/users
        - Method=POST
        filters:
        - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      
      - id: users-ws-update-delete
        uri: lb://user-ws
        predicates:
        - Path=/user-ws/users/*
        - Method=GET,PUT,DELETE
        - Header=Authorization, Bearer (.*)
        filters:
        - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
        - AuthorizationHeaderFilter
        
      - id: account-ws-all
        uri: lb://account-ws
        predicates:
        - Path=/account-ws/accounttypes
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/account-ws/(?<segment>.*), /$\{segment}
                
      - id: account-ws-getById
        uri: lb://account-ws
        predicates:
        - Path=/account-ws/accounttypes/*
        - Method=GET
        filters:
        - RewritePath=/account-ws/(?<segment>.*), /$\{segment}
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
token:
  secret : mysecretmysecretmysecretmysecretxxddgdg